name: Docker

on:
  workflow_call:
  
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.2.1
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: binarios
        
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: patrickcaloriocarvalho
        password: ${{ secrets.PASSWORD_DOCKERHUB }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: patrickcaloriocarvalho/ci_com_go:${{github.ref_name}}
    
    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: xz
        GHR_PATH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
